const fs = require("fs");
const path = require("path");
const attributes = require("./serverless/cloudformation/resource.attributes.schema.json");

(async () => {
    const sharedAttributes = {
        "DeletionPolicy": {
          "description": "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html",
          "type": "string",
          "enum": [
            "Delete",
            "Retain",
            "Snapshot"
          ]
        },
        "UpdateReplacePolicy": {
          "description": "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html",
          "type": "string",
          "enum": [
            "Delete",
            "Retain",
            "Snapshot"
          ]
        },
        "Metadata": {
          "description": "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html",
          "type": "object"
        },
        "CreationPolicy": {
          "description": "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html",
          "type": "object"
        },
        "UpdatePolicy": {
          "description": "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html",
          "type": "object"
        },
        "DependsOn": {
          "type": [
            "string",
            "array"
          ],
          "items": {
            "type": "string"
          }
        }
    }
    /**
     * These resource files are downloaded from cloudformation for us-east-1
     * https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html
     */
    const resources = fs.readdirSync(path.join(__dirname, "serverless/cloudformation/resources"));
    const resourcesSchema = {
        $comment: "DO NOT EDIT THIS FILE DIRECTLY! PLEASE CHANGE THE INDIVIDUAL RESOURCE FILES AND THEN RUN THE SCRIPT TO GENERATE THIS FILE",
        $schema: "http://json-schema.org/draft-07/schema#",
        $id: "https://aws.amazon.com/cloudformation/resources.schema.json",
        definitions: {},
        description: "Auto generated schema from individual resource definition from Cloudformation",
        type: "object",
        properties: {}
    }
    for (const resource of resources) {
        const schema = require(`./serverless/cloudformation/resources/${resource}`);
        resourcesSchema.definitions[schema.typeName.split("::").join("")] = {
            title: schema.typeName.split("::").join(""),
            type: "object",
            additionalProperties: false,
            properties: {
                Type: {
                    type: "string",
                    enum: [
                        schema.typeName
                    ],
                },
                Properties: {
                    $ref: `resources/${resource}`
                },
                ...sharedAttributes
            },
            required: [
              "Type",
              "Properties"
            ]
        }
    }
    resourcesSchema.properties = {
        Resources: {
            type: "object",
            minProperties: 1,
            patternProperties: {
                "^[a-zA-Z0-9]{1,255}$": {
                    oneOf: Object.keys(resourcesSchema.definitions).map((d) => {
                        return {
                            $ref: "#/definitions/" + d
                        }
                    })
                }
            }
        }
    }
    fs.writeFileSync(
        path.join(__dirname, "serverless/cloudformation/resources.schema.json"),
        JSON.stringify(resourcesSchema, null, 4)
    )
})()
